// Mock data for development — replace with real API calls when backend is ready

import type { Job, Application, User, Rating } from '../types';

export const MOCK_USER: User = {
  id: 'user-001',
  phone: '+919876543210',
  firebase_uid: 'firebase-uid-001',
  name: 'Raju Kumar',
  age: 26,
  bio: 'Hard working delivery partner with 2 years experience.',
  avatar_url: null,
  skills: ['Delivery', 'Driver', 'Shop Helper'],
  language: 'en',
  location_lat: 17.4344,
  location_lng: 78.4497,
  location_name: 'Ameerpet, Hyderabad',
  jobs_completed: 12,
  jobs_posted: 3,
  worker_rating: 4.7,
  employer_rating: 4.5,
  total_reviews: 9,
  is_verified: false,
  is_blocked: false,
  expo_push_token: null,
  created_at: '2024-01-15T10:00:00Z',
  updated_at: '2024-06-01T10:00:00Z',
};

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-001',
    poster_id: 'user-002',
    title: 'Delivery Partner Needed',
    category: 'delivery',
    description: 'Need 2 delivery partners for grocery delivery in Ameerpet area. Must have own bike and valid driving license. Work is from 9AM to 6PM daily. Meals provided during shift. Weekly payment every Monday.',
    pay_amount: 600,
    pay_type: 'day',
    hours_per_day: 9,
    quantity_total: 5,
    quantity_hired: 3,
    location_lat: 17.4344,
    location_lng: 78.4497,
    location_name: 'Ameerpet X Roads, Hyderabad',
    duration_text: 'Ongoing',
    is_urgent: true,
    show_phone: false,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Ramesh Sharma',
    poster_rating: 4.8,
    poster_avatar: null,
    distance_km: 0.4,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: false,
    travel_allowance: true,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-002',
    poster_id: 'user-003',
    title: 'Event Staff — 1 Day',
    category: 'events',
    description: 'Need 10 event staff members for a wedding function in Jubilee Hills. Smart casuals required. Meals provided.',
    pay_amount: 150,
    pay_type: 'hour',
    hours_per_day: 10,
    quantity_total: 10,
    quantity_hired: 6,
    location_lat: 17.4239,
    location_lng: 78.4097,
    location_name: 'Jubilee Hills, Hyderabad',
    is_urgent: false,
    show_phone: true,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Priya K.',
    poster_rating: 4.6,
    poster_avatar: null,
    distance_km: 1.2,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: true,
    travel_allowance: true,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-003',
    poster_id: 'user-004',
    title: 'Shop Helper — Monthly',
    category: 'shop',
    description: 'Looking for a reliable shop helper for our kirana store. Work includes stocking shelves, billing assistance, and home delivery. Full training provided.',
    pay_amount: 8000,
    pay_type: 'month',
    hours_per_day: 8,
    quantity_total: 2,
    quantity_hired: 1,
    location_lat: 17.4850,
    location_lng: 78.4102,
    location_name: 'Kukatpally, Hyderabad',
    is_urgent: false,
    show_phone: false,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Balaji N.',
    poster_rating: 4.9,
    poster_avatar: null,
    distance_km: 2.8,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: false,
    travel_allowance: false,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-004',
    poster_id: 'user-005',
    title: 'Construction Labour Needed',
    category: 'construction',
    description: 'Need skilled construction workers for foundation work at residential project. Safety equipment provided.',
    pay_amount: 700,
    pay_type: 'day',
    hours_per_day: 9,
    quantity_total: 8,
    quantity_hired: 4,
    location_lat: 17.3616,
    location_lng: 78.4747,
    location_name: 'Mehdipatnam, Hyderabad',
    is_urgent: true,
    show_phone: true,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Suresh B.',
    poster_rating: 4.3,
    poster_avatar: null,
    distance_km: 3.5,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: '3 Days',
    work_type: 'part_time',
    skill_level: 'beginner',
    payment_schedule: 'weekly',
    food_included: false,
    stay_included: false,
    travel_allowance: false,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-005',
    poster_id: 'user-006',
    title: 'Restaurant Helper Wanted',
    category: 'restaurant',
    description: 'South Indian restaurant needs serving staff and kitchen helpers. Experience preferred but not mandatory. Good tips from customers.',
    pay_amount: 250,
    pay_type: 'hour',
    hours_per_day: 8,
    quantity_total: 3,
    quantity_hired: 0,
    location_lat: 17.4502,
    location_lng: 78.3811,
    location_name: 'Gachibowli, Hyderabad',
    is_urgent: false,
    show_phone: false,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 43200000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Anitha R.',
    poster_rating: 4.7,
    poster_avatar: null,
    distance_km: 4.1,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: '1 Day',
    work_type: 'one_time',
    skill_level: 'any',
    payment_schedule: 'daily',
    food_included: false,
    stay_included: false,
    travel_allowance: false,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-006',
    poster_id: 'user-009',
    title: 'Office Data Entry Operator',
    category: 'office',
    description: 'Looking for a temporary data entry operator for 2 weeks. Must have basic knowledge of Excel and fast typing speed. Work location near Ameerpet.',
    pay_amount: 500,
    pay_type: 'day',
    hours_per_day: 6,
    quantity_total: 2,
    quantity_hired: 1,
    location_lat: 17.4360,
    location_lng: 78.4485,
    location_name: 'Ameerpet Metro, Hyderabad',
    is_urgent: false,
    show_phone: true,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Tech Solutions Ltd.',
    poster_rating: 4.5,
    poster_avatar: null,
    distance_km: 0.2,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: true,
    travel_allowance: true,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-007',
    poster_id: 'user-010',
    title: 'Office & Cafe Cleaning Help',
    category: 'cleaning',
    description: 'Urgent requirement for deep cleaning of our office and small pantry area. Materials and tools will be provided. Expected time: 5 hours.',
    pay_amount: 800,
    pay_type: 'day',
    hours_per_day: 5,
    quantity_total: 1,
    quantity_hired: 0,
    location_lat: 17.4320,
    location_lng: 78.4520,
    location_name: 'SR Nagar, Hyderabad',
    is_urgent: true,
    show_phone: false,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Indie Brew Cafe',
    poster_rating: 4.9,
    poster_avatar: null,
    distance_km: 0.6,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: true,
    travel_allowance: true,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-008',
    poster_id: 'user-011',
    title: 'Night Security Guard',
    category: 'security',
    description: 'Need a reliable night security guard for our retail showroom in Jubilee Hills. Hours: 8 PM to 8 AM. Guard outfit provided. Safe and clean environment.',
    pay_amount: 12000,
    pay_type: 'month',
    hours_per_day: 12,
    quantity_total: 1,
    quantity_hired: 0,
    location_lat: 17.4250,
    location_lng: 78.4120,
    location_name: 'Jubilee Hills Rd 36, Hyderabad',
    is_urgent: false,
    show_phone: false,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Vogue Apparels',
    poster_rating: 4.6,
    poster_avatar: null,
    distance_km: 1.1,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: true,
    travel_allowance: true,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-009',
    poster_id: 'user-012',
    title: 'Outstation Driver (2 Days)',
    category: 'driver',
    description: 'Looking for an experienced chauffeur to drive an automatic SUV from Hyderabad to Vijayawada and back for a weekend family trip. Food & stay covered.',
    pay_amount: 1500,
    pay_type: 'day',
    hours_per_day: 10,
    quantity_total: 1,
    quantity_hired: 0,
    location_lat: 17.4350,
    location_lng: 78.4410,
    location_name: 'Begumpet, Hyderabad',
    is_urgent: true,
    show_phone: true,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Satish Chandra',
    poster_rating: 4.8,
    poster_avatar: null,
    distance_km: 0.8,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: '3 Days',
    work_type: 'part_time',
    skill_level: 'beginner',
    payment_schedule: 'weekly',
    food_included: false,
    stay_included: false,
    travel_allowance: false,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-010',
    poster_id: 'user-013',
    title: 'Office WiFi & Router Setup',
    category: 'tech',
    description: 'Need a tech assistant to configure a high-speed WiFi router and hook up 3 wireless office printers. Fast gig for anyone with standard networking knowledge.',
    pay_amount: 1200,
    pay_type: 'day',
    hours_per_day: 3,
    quantity_total: 1,
    quantity_hired: 0,
    location_lat: 17.4410,
    location_lng: 78.4520,
    location_name: 'Sanjeeva Reddy Nagar, Hyderabad',
    is_urgent: false,
    show_phone: false,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 18000000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Focus Coworking',
    poster_rating: 4.4,
    poster_avatar: null,
    distance_km: 0.7,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: true,
    travel_allowance: true,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-011',
    poster_id: 'user-014',
    title: 'Makeup & Hair Assistant',
    category: 'salon',
    description: 'Looking for a temporary assistant beautician for bridal makeup and basic hair styling for a pre-wedding shoot. Transportation provided.',
    pay_amount: 2500,
    pay_type: 'day',
    hours_per_day: 6,
    quantity_total: 1,
    quantity_hired: 0,
    location_lat: 17.4100,
    location_lng: 78.4300,
    location_name: 'Banjara Hills, Hyderabad',
    is_urgent: false,
    show_phone: true,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Glow Unisex Salon',
    poster_rating: 4.7,
    poster_avatar: null,
    distance_km: 1.8,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: 'Ongoing',
    work_type: 'full_time',
    skill_level: 'skilled',
    payment_schedule: 'monthly',
    food_included: true,
    stay_included: false,
    travel_allowance: true,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
  {
    id: 'job-012',
    poster_id: 'user-015',
    title: 'Class 10 Math Home Tutor',
    category: 'tutor',
    description: 'Need a home tutor for teaching Class 10 CBSE Math to my son. 3 sessions a week, 1.5 hours per session. Professional experience required.',
    pay_amount: 400,
    pay_type: 'hour',
    hours_per_day: 2,
    quantity_total: 1,
    quantity_hired: 0,
    location_lat: 17.4560,
    location_lng: 78.4350,
    location_name: 'Yousufguda, Hyderabad',
    is_urgent: false,
    show_phone: false,
    status: 'live',
    is_deleted: false,
    created_at: new Date(Date.now() - 21600000).toISOString(),
    updated_at: new Date().toISOString(),
    poster_name: 'Kiran Kumar',
    poster_rating: 4.9,
    poster_avatar: null,
    distance_km: 1.5,
    work_start_date: '2026-08-10',
    work_end_date: '2026-08-15',
    work_start_time: '09:00 AM',
    work_end_time: '06:00 PM',
    duration_text: '1 Day',
    work_type: 'one_time',
    skill_level: 'any',
    payment_schedule: 'daily',
    food_included: false,
    stay_included: false,
    travel_allowance: false,
    language_pref: 'Telugu, Hindi',
    contact_phone: '+919876543210'
  },
];

export const MOCK_RECEIVED_APPLICATIONS: Application[] = [
  {
    id: 'app-001',
    job_id: 'job-001',
    applicant_id: 'user-007',
    employer_id: 'user-001',
    description: 'I have 2 years experience in delivery. I have own bike and license. I am available from tomorrow morning.',
    voice_url: null,
    status: 'pending',
    applied_at: new Date(Date.now() - 120000).toISOString(),
    responded_at: null,
    completed_at: null,
    applicant: {
      ...MOCK_USER,
      id: 'user-007',
      name: 'Raju Kumar',
      worker_rating: 4.7,
      jobs_completed: 18,
    },
    job: MOCK_JOBS[0],
  },
  {
    id: 'app-002',
    job_id: 'job-001',
    applicant_id: 'user-008',
    employer_id: 'user-001',
    description: 'Ready to work immediately. I know all routes in Ameerpet area.',
    voice_url: null,
    status: 'pending',
    applied_at: new Date(Date.now() - 900000).toISOString(),
    responded_at: null,
    completed_at: null,
    applicant: {
      ...MOCK_USER,
      id: 'user-008',
      name: 'Suresh Mani',
      worker_rating: 4.2,
      jobs_completed: 7,
    },
    job: MOCK_JOBS[0],
  },
];

export const MOCK_SENT_APPLICATIONS: Application[] = [
  {
    id: 'app-003',
    job_id: 'job-002',
    applicant_id: 'user-001',
    employer_id: 'user-003',
    description: 'I am experienced in event management. Available for the full day.',
    voice_url: null,
    status: 'accepted',
    applied_at: new Date(Date.now() - 3600000).toISOString(),
    responded_at: new Date(Date.now() - 1800000).toISOString(),
    completed_at: null,
    job: MOCK_JOBS[1],
    employer: {
      ...MOCK_USER,
      id: 'user-003',
      name: 'QuickMart Store',
      employer_rating: 4.8,
    },
  },
  {
    id: 'app-004',
    job_id: 'job-003',
    applicant_id: 'user-001',
    employer_id: 'user-004',
    description: 'Interested in shop helper role.',
    voice_url: null,
    status: 'rejected',
    applied_at: new Date(Date.now() - 10800000).toISOString(),
    responded_at: new Date(Date.now() - 7200000).toISOString(),
    completed_at: null,
    job: MOCK_JOBS[2],
    employer: {
      ...MOCK_USER,
      id: 'user-004',
      name: 'Balaji Kirana',
      employer_rating: 4.9,
    },
  },
];

export const MOCK_COMPLETED_APPLICATIONS: Application[] = [
  {
    id: 'app-005',
    job_id: 'job-007',
    applicant_id: 'user-001',
    employer_id: 'user-009',
    description: 'Ready to work hard.',
    voice_url: null,
    status: 'completed',
    applied_at: new Date(Date.now() - 604800000).toISOString(),
    responded_at: new Date(Date.now() - 601200000).toISOString(),
    completed_at: new Date(Date.now() - 86400000).toISOString(),
    job: {
      ...MOCK_JOBS[0],
      id: 'job-007',
      title: 'Event Setup Staff',
      category: 'events',
    },
    employer: {
      ...MOCK_USER,
      id: 'user-009',
      name: 'Srikanth Events',
      employer_rating: 4.5,
    },
  },
];

export const MOCK_MY_POSTED_JOBS: Job[] = [
  { ...MOCK_JOBS[0], poster_id: 'user-001', status: 'live' },
  {
    ...MOCK_JOBS[1],
    id: 'job-my-002',
    poster_id: 'user-001',
    title: 'House Cleaning Help',
    status: 'paused',
    quantity_total: 2,
    quantity_hired: 0,
  },
  {
    ...MOCK_JOBS[2],
    id: 'job-my-003',
    poster_id: 'user-001',
    title: 'Security Guard — Night Shift',
    status: 'filled',
    quantity_total: 3,
    quantity_hired: 3,
  },
];

export const MOCK_RATINGS: Rating[] = [
  {
    id: 'rating-001',
    application_id: 'app-005',
    rater_id: 'user-009',
    ratee_id: 'user-001',
    rating_type: 'worker',
    stars: 5,
    tags: ['Punctual', 'Hard worker', 'Reliable'],
    review_text: 'Excellent worker. Very punctual and hardworking. Would hire again!',
    is_deleted: false,
    is_reported: false,
    created_at: new Date(Date.now() - 172800000).toISOString(),
    rater: { ...MOCK_USER, id: 'user-009', name: 'Srikanth Events' },
  },
  {
    id: 'rating-002',
    application_id: 'app-006',
    rater_id: 'user-010',
    ratee_id: 'user-001',
    rating_type: 'worker',
    stars: 4,
    tags: ['Honest', 'Reliable'],
    review_text: 'Good work. Completed task on time.',
    is_deleted: false,
    is_reported: false,
    created_at: new Date(Date.now() - 604800000).toISOString(),
    rater: { ...MOCK_USER, id: 'user-010', name: 'Arjun R.' },
  },
];
